-- Announcements.
--
-- deskripsi is nullable: the admin screens never supply it.
-- Overlaps notifikasi_beranda, which drives homepage announcements; the two are
-- kept separate because both hold live data.

BEGIN;

CREATE TABLE pemberitahuan (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul      VARCHAR(255) NOT NULL,
    deskripsi  TEXT,
    foto       VARCHAR(255),
    link_url   VARCHAR(500),
    is_active  BOOLEAN     NOT NULL DEFAULT TRUE,
    urutan     INTEGER     NOT NULL DEFAULT 0,
    tipe       VARCHAR(10) NOT NULL DEFAULT 'notif',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pemberitahuan_tipe_chk CHECK (tipe IN ('notif','modal'))
);

-- Both read paths filter on tipe and is_active, then order.
CREATE INDEX pemberitahuan_tipe_active_idx ON pemberitahuan (tipe, is_active, urutan);

COMMIT;
