-- Contact and complaint messages.
--
-- ticket_code is the only credential for reading a ticket back, so it is random
-- rather than sequential: a counter would let anyone enumerate other people's
-- complaints.

BEGIN;

CREATE TABLE contact_messages (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code VARCHAR(32)  NOT NULL,
    nama        VARCHAR(255) NOT NULL,
    telepon     VARCHAR(50),
    email       VARCHAR(255),
    kategori    VARCHAR(100),
    subjek      VARCHAR(255),
    pesan       TEXT         NOT NULL,
    status      VARCHAR(20)  NOT NULL DEFAULT 'baru',
    catatan     TEXT,
    ip_address  VARCHAR(45),
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT contact_messages_status_chk
        CHECK (status IN ('baru','diproses','selesai','ditolak'))
);

CREATE UNIQUE INDEX contact_messages_ticket_key ON contact_messages (ticket_code);
CREATE INDEX contact_messages_status_created_idx ON contact_messages (status, created_at);

COMMIT;
