export const prerender = false;

import { createArticle } from "../../lib/services/article.service";
import { hasFile, uploadFile } from "../../lib/services/content.service";
import { verifyCsrf } from "../../lib/session";

export async function POST({ request, locals }) {
  const formData = await request.formData();

  if (!verifyCsrf(locals.session, formData.get("_csrf"))) {
    return new Response("Invalid CSRF token.", { status: 403 });
  }

  // The stored filename is generated by the API. This endpoint used to write
  // formData.get("picture").name straight into public/uploads, so a crafted
  // filename could escape the directory.
  let picture = "";
  const file = formData.get("picture");
  if (hasFile(file)) {
    const uploaded = await uploadFile(file, "artikel", "public");
    if (!uploaded.ok) {
      return new Response(uploaded.message, { status: 400 });
    }
    picture = uploaded.key;
  }

  const result = await createArticle({
    category_id: Number(formData.get("category")),
    title: formData.get("title")?.toString() ?? "",
    content: formData.get("content")?.toString() ?? "",
    is_active: (formData.get("active")?.toString() ?? "Y") === "Y",
    picture,
    editor: locals.session?.sub ?? "",
  });

  if (!result.ok) {
    return new Response(result.message, { status: 422 });
  }

  // 303 so a refresh does not repost the form.
  return new Response(null, { status: 303, headers: { Location: "/admin/artikel" } });
}
