SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS inovasi_layanan;
DROP TABLE IF EXISTS tempat_pelayanan_dpmptsp;
DROP TABLE IF EXISTS tempat_layanan;
DROP TABLE IF EXISTS ppid_item;
DROP TABLE IF EXISTS ppid_kategori;
DROP TABLE IF EXISTS informasi_section_item;
DROP TABLE IF EXISTS informasi_section;
DROP TABLE IF EXISTS pelayanan_standar;
DROP TABLE IF EXISTS aplikasi_publik;
DROP TABLE IF EXISTS regulasi;
DROP TABLE IF EXISTS notifikasi_beranda;
DROP TABLE IF EXISTS header_menu;
DROP TABLE IF EXISTS website_pengaturan;
DROP TABLE IF EXISTS tentang_kami;
DROP TABLE IF EXISTS tentang_slider;
DROP TABLE IF EXISTS tentang_dpmptsp;
DROP TABLE IF EXISTS twdata;
DROP TABLE IF EXISTS renstra_investasi;
DROP TABLE IF EXISTS peta_investasi;
DROP TABLE IF EXISTS videos;
DROP TABLE IF EXISTS keunggulan;
DROP TABLE IF EXISTS beranda_slider;
DROP TABLE IF EXISTS beranda_dpmptsp;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS category_berita;
SET FOREIGN_KEY_CHECKS = 1;
