-- Baseline schema (MySQL). Generated from the Postgres migration.
--
-- Fifteen tables are ported from a dump of the legacy `ladpm` database. Ten are
-- reconstructed from the application's queries because no DDL for them exists;
-- their column names are certain, their types are inferred, and each is marked
-- RECONSTRUCTED below. `users` is new.
--
-- Differences from the legacy schema:
--   TentangKamisWebV5 -> tentang_kami   (mixed-case identifiers)
--   user              -> users          (reserved word in Postgres)
--   enum('Y','N') and integer flags -> boolean
--   post.date + post.time           -> published_at
--   ENUM                            -> VARCHAR + CHECK
--   post gains an indexed slug column
--
-- Identity columns are GENERATED BY DEFAULT so imported rows can keep their ids.
-- Dropped: hero_slider, posts, translations.

BEGIN;

-- ============================================================ articles =====
CREATE TABLE category_berita (
    id_category  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title        VARCHAR(50)  NOT NULL,
    is_active    TINYINT(1)      NOT NULL DEFAULT 1,
    created_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE post (
    id_post        INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    id_category    INTEGER      NOT NULL,
    -- Added, not ported. Its absence is why media/[slug].astro loads all 553
    -- rows and slugifies each one in JS to find a single article.
    slug           VARCHAR(255) NOT NULL,
    title          VARCHAR(200) NOT NULL DEFAULT '',
    content        TEXT         NOT NULL,
    ref_content    TEXT         NOT NULL,
    seotitle       VARCHAR(200) NOT NULL DEFAULT '',
    tag            VARCHAR(200) NOT NULL DEFAULT '',
    -- date + time collapsed into one column, so ORDER BY is indexable.
    published_at   TIMESTAMP  NOT NULL,
    editor         VARCHAR(100) NOT NULL DEFAULT '',
    is_active      TINYINT(1)      NOT NULL DEFAULT 1,
    is_headline    TINYINT(1)      NOT NULL DEFAULT 0,
    picture        VARCHAR(255) NOT NULL DEFAULT '',
    hits           INTEGER      NOT NULL DEFAULT 0,
    title_en       VARCHAR(200),
    content_en     TEXT,
    ref_content_en TEXT,
    created_at     TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT post_category_fk FOREIGN KEY (id_category)
        REFERENCES category_berita (id_category) ON DELETE RESTRICT,
    FULLTEXT KEY post_fulltext_idx (title, content)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX post_slug_key         ON post (slug);
CREATE INDEX post_published_idx           ON post (published_at);
CREATE INDEX post_category_published_idx  ON post (id_category, published_at);
CREATE INDEX post_active_published_idx    ON post (is_active, published_at);

-- ======================================================== home page ========
CREATE TABLE beranda_dpmptsp (
    -- Primary key added: the source table had `id int NOT NULL DEFAULT 0` and
    -- no key at all.
    id      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipe    VARCHAR(20) NOT NULL,
    konten  TEXT    NOT NULL,
    urutan  INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT beranda_dpmptsp_tipe_chk CHECK (tipe IN ('judul','paragraf','link'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE beranda_slider (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  -- added
    gambar     VARCHAR(255) NOT NULL,
    judul      VARCHAR(150),
    deskripsi  TEXT,
    urutan     INTEGER NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE keunggulan (
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    judul       VARCHAR(255) NOT NULL,
    deskripsi   TEXT         NOT NULL,
    icon        VARCHAR(100) NOT NULL,
    warna_icon  VARCHAR(20)  DEFAULT 'blue-600',
    warna_bg    VARCHAR(20)  DEFAULT 'blue-100',
    link        VARCHAR(255) DEFAULT '#',
    tanggal     TIMESTAMP  DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE videos (
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    judul       VARCHAR(255) NOT NULL,
    deskripsi   TEXT,
    thumbnail   VARCHAR(255),
    url_video   VARCHAR(255),
    status      VARCHAR(10) NOT NULL DEFAULT 'lama',
    tanggal     DATE        NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT videos_status_chk CHECK (status IN ('baru','lama'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ======================================================== investment =======
CREATE TABLE peta_investasi (
    id                INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    judul             VARCHAR(255),
    deskripsi         TEXT,
    gambar            VARCHAR(255),
    link              VARCHAR(255),
    judul_renstra     VARCHAR(255),
    deskripsi_renstra TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE renstra_investasi (
    id      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipe    VARCHAR(20) NOT NULL,
    konten  TEXT    NOT NULL,
    urutan  INTEGER NOT NULL DEFAULT 0,
    -- A separate constraint from beranda_dpmptsp.tipe on purpose: this domain
    -- has a fourth value. They overlap; they are not the same thing.
    CONSTRAINT renstra_investasi_tipe_chk CHECK (tipe IN ('judul','paragraf','wilayah','link'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE twdata (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tw_option  VARCHAR(50)  NOT NULL,
    file_path  VARCHAR(255) NOT NULL,
    created_at TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ============================================================ about ========
CREATE TABLE tentang_dpmptsp (
    id      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipe    VARCHAR(20) NOT NULL,
    konten  TEXT    NOT NULL,
    urutan  INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT tentang_dpmptsp_tipe_chk CHECK (tipe IN ('judul','paragraf','link'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE tentang_slider (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    gambar     VARCHAR(255) NOT NULL,
    judul      VARCHAR(150),
    deskripsi  TEXT,
    urutan     INTEGER NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Renamed from TentangKamisWebV5, whose mixed-case name and columns are the
-- only naming problem here that is a genuine defect.
CREATE TABLE tentang_kami (
    id           INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  -- was Id_Konten
    nama         TEXT,          -- was Nama_Konten
    isi          TEXT,          -- was Isi_Konten
    foto         VARCHAR(500),  -- was Foto_Konten
    judul        VARCHAR(500),  -- was Judul_Konten
    keterangan   VARCHAR(500),  -- was Keterangan
    tags         TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ---------------------------------------------------- RECONSTRUCTED ---
-- No DDL exists for the tables below. Column names come from the queries
-- that read them; types, lengths and nullability are inferred.

-- RECONSTRUCTED
CREATE TABLE website_pengaturan (
    id     INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nama   VARCHAR(255) NOT NULL,
    logo   VARCHAR(500)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED
-- parent_id = 0 and NULL as equivalent, so the FK allows only NULL.
CREATE TABLE header_menu (
    id             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    parent_id      INTEGER,
    nama           VARCHAR(255) NOT NULL,
    url            VARCHAR(500),
    urutan         INTEGER NOT NULL DEFAULT 0,
    is_active      TINYINT(1) NOT NULL DEFAULT 1,   -- was aktif tinyint
    tipe           VARCHAR(50),
    tombol_kontak  TINYINT(1) NOT NULL DEFAULT 0,
    CONSTRAINT header_menu_parent_fk FOREIGN KEY (parent_id)
        REFERENCES header_menu (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE INDEX header_menu_parent_urutan_idx ON header_menu (parent_id, urutan);

-- RECONSTRUCTED
CREATE TABLE notifikasi_beranda (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    judul      VARCHAR(255) NOT NULL,
    isi        TEXT,
    gambar     VARCHAR(500),
    tipe       VARCHAR(50),
    icon       VARCHAR(100),
    link       VARCHAR(500),
    teks_link  VARCHAR(255),
    is_active  TINYINT(1) NOT NULL DEFAULT 1,
    mulai      TIMESTAMP,
    selesai    TIMESTAMP,
    urutan     INTEGER NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE INDEX notifikasi_beranda_window_idx ON notifikasi_beranda (is_active, mulai, selesai);

-- RECONSTRUCTED
CREATE TABLE regulasi (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    jenis      VARCHAR(100),
    nomor      VARCHAR(100),
    tahun      INTEGER,
    judul      TEXT NOT NULL,
    file       VARCHAR(500),
    is_active  TINYINT(1) NOT NULL DEFAULT 1,
    urutan     INTEGER NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE INDEX regulasi_active_urutan_idx ON regulasi (is_active, urutan, tahun);

-- RECONSTRUCTED
CREATE TABLE aplikasi_publik (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nama       VARCHAR(255) NOT NULL,
    deskripsi  TEXT,
    url        VARCHAR(500),
    icon       VARCHAR(100),
    target     VARCHAR(20),
    is_active  TINYINT(1) NOT NULL DEFAULT 1,
    urutan     INTEGER NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED
-- parses with JSON.parse. Stored as TEXT and decoded in Go rather than JSONB:
-- it is never queried by JSON path, so JSONB buys nothing and costs the MySQL
-- migration its equivalence.
CREATE TABLE pelayanan_standar (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tab_key    VARCHAR(100) NOT NULL,
    tab_icon   VARCHAR(100),
    tab_judul  VARCHAR(255),
    judul      VARCHAR(255),
    deskripsi  TEXT,
    isi        TEXT,
    urutan     INTEGER NOT NULL DEFAULT 0,
    is_active  TINYINT(1) NOT NULL DEFAULT 1   -- was status tinyint
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED
-- looks rows up by ('info-sec'), so it is UNIQUE and the child table points at
-- it rather than at the surrogate id.
CREATE TABLE informasi_section (
    id                  INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    section_id          VARCHAR(100) NOT NULL UNIQUE,
    badge               VARCHAR(255),
    judul               VARCHAR(255),
    judul_highlight     VARCHAR(255),
    deskripsi           TEXT,
    icon                VARCHAR(100),
    subjudul            VARCHAR(255),
    subjudul_keterangan TEXT,
    isi                 TEXT,
    akses_judul         VARCHAR(255),
    akses_deskripsi     TEXT,
    akses_button        VARCHAR(255),
    akses_link          VARCHAR(500),
    email_label         VARCHAR(255),
    email               VARCHAR(255),
    email_button        VARCHAR(255),
    alamat_label        VARCHAR(255),
    nama_instansi       VARCHAR(255),
    alamat              TEXT,
    cta_judul           VARCHAR(255),
    cta_deskripsi       TEXT,
    cta_button          VARCHAR(255),
    cta_link            VARCHAR(500),
    is_active           TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED
CREATE TABLE informasi_section_item (
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    section_id  VARCHAR(100) NOT NULL,
    icon        VARCHAR(100),
    judul       VARCHAR(255),
    deskripsi   TEXT,
    warna       VARCHAR(50),
    urutan      INTEGER NOT NULL DEFAULT 0,
    is_active   TINYINT(1) NOT NULL DEFAULT 1,
    CONSTRAINT informasi_section_item_section_fk FOREIGN KEY (section_id)
        REFERENCES informasi_section (section_id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE INDEX informasi_section_item_section_idx ON informasi_section_item (section_id, urutan);

-- RECONSTRUCTED
CREATE TABLE ppid_kategori (
    id             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nama_kategori  VARCHAR(255) NOT NULL,
    slug           VARCHAR(255) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED
CREATE TABLE ppid_item (
    id           INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    kategori_id  INTEGER NOT NULL,
    judul        TEXT NOT NULL,
    isi          TEXT,
    file_url     VARCHAR(500),
    urutan       INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT ppid_item_kategori_fk FOREIGN KEY (kategori_id)
        REFERENCES ppid_kategori (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE INDEX ppid_item_kategori_urutan_idx ON ppid_item (kategori_id, urutan);

-- RECONSTRUCTED
CREATE TABLE tempat_layanan (
    id         INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    judul      VARCHAR(255) NOT NULL,
    deskripsi  TEXT,
    gambar     VARCHAR(500),
    alt_text   VARCHAR(255),
    lokasi     VARCHAR(255),
    alamat     TEXT,
    warna      VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED
-- taken from what the template renders, so this is the weakest reconstruction
-- here.
CREATE TABLE tempat_pelayanan_dpmptsp (
    id          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    title       VARCHAR(255),
    image_path  VARCHAR(500),
    alt_text    VARCHAR(255),
    location    VARCHAR(255),
    alamat      TEXT,
    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE INDEX tempat_pelayanan_created_idx ON tempat_pelayanan_dpmptsp (created_at);

-- RECONSTRUCTED
CREATE TABLE inovasi_layanan (
    id              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    slug            VARCHAR(255) NOT NULL UNIQUE,
    nama            VARCHAR(255) NOT NULL,
    singkatan       VARCHAR(100),
    kategori        VARCHAR(100),
    deskripsi       TEXT,
    rancang_bangun  TEXT,
    tujuan          TEXT,
    manfaat         TEXT,
    hasil           TEXT,
    tahun_usulan    INTEGER,
    tahapan         VARCHAR(100),
    jenis           VARCHAR(100),
    gambar          VARCHAR(500),
    url_layanan     VARCHAR(500),
    url_label       VARCHAR(255),
    icon            VARCHAR(100),
    warna           VARCHAR(50),
    urutan          INTEGER NOT NULL DEFAULT 0,
    is_active       TINYINT(1) NOT NULL DEFAULT 1,   -- was status
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- RECONSTRUCTED. Replaces the legacy `user` table; passwords are argon2id or
-- bcrypt PHC strings and no existing credential is migrated.
CREATE TABLE users (
    id             INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username       VARCHAR(100) NOT NULL UNIQUE,
    email          VARCHAR(255),
    password_hash  TEXT NOT NULL,
    role           VARCHAR(50) NOT NULL DEFAULT 'admin',
    is_active      TINYINT(1) NOT NULL DEFAULT 1,
    last_login_at  TIMESTAMP,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

COMMIT;
