// Where legacy media is served from.
import { optionalEnv } from "@dpmptsp/config";

export const MEDIA_BASE_URL = optionalEnv(
  "MEDIA_BASE_URL",
  "https://dpm-ptsp.surabaya.go.id"
).replace(/\/+$/, "");

/** Builds a media URL from a root-relative path. */
export function mediaUrl(path: string): string {
  return `${MEDIA_BASE_URL}/${String(path).replace(/^\/+/, "")}`;
}

/**
 * Resolves a stored image reference to a URL.
 *
 * Two shapes exist side by side. Rows written before the API owned uploads hold
 * a bare filename that lives in public/uploads; rows written since hold a key
 * generated by the storage layer, which always contains a slash. Keeping both
 * working is what lets the two eras coexist without a data migration.
 */
export function uploadUrl(
  ref: string | null | undefined,
  fallback = "",
  legacyDir = ""
): string {
  const value = String(ref ?? "").trim();
  if (!value) return fallback;
  if (/^(https?:)?\/\//.test(value)) return value;
  if (value.startsWith("/")) return value;
  if (value.includes("/")) return `/storage/${value}`;
  const dir = legacyDir ? `${legacyDir.replace(/^\/+|\/+$/g, "")}/` : "";
  return `/uploads/${dir}${value}`;
}
